The Nobel Prize has been among the most prestigious international awards since 1901. Each year, awards are bestowed in chemistry, literature, physics, physiology or medicine, economics, and peace. In addition to the honor, prestige, and substantial prize money, the recipient also gets a gold medal with an image of Alfred Nobel (1833 - 1896), who established the prize.

![](Nobel_Prize.png)

The Nobel Foundation has made a dataset available of all prize winners from the outset of the awards from 1901 to 2023. The dataset used in this project is from the Nobel Prize API and is available in the `nobel.csv` file in the `data` folder.

In this project, you'll get a chance to explore and answer several questions related to this prizewinning data. And we encourage you then to explore further questions that you're interested in!

In [1]:
# Loading in required libraries
import pandas as pd
import seaborn as sns
import numpy as np

# Start coding here!
df_nobel = pd.read_csv(r'data/nobel.csv')
df_nobel.head()

   year    category  ... death_city death_country
0  1901   Chemistry  ...     Berlin       Germany
1  1901  Literature  ...   Châtenay        France
2  1901    Medicine  ...    Marburg       Germany
3  1901       Peace  ...     Heiden   Switzerland
4  1901       Peace  ...      Paris        France

[5 rows x 18 columns]

In [10]:
top_gender = pd.DataFrame(df_nobel['sex'].value_counts()).reset_index().loc[0,'index']
top_country = pd.DataFrame(df_nobel['birth_country'].value_counts()).reset_index().loc[0,'index']
print(top_gender, top_country)

Male United States of America

In [89]:
def df_category_ratio(cat_column, cat_value, groupby, df):
    value_counts = df[df[cat_column]==cat_value].groupby(groupby).size()
    cat_counts = df.groupby(groupby)[cat_column].size()
    max_decade = pd.DataFrame((value_counts/cat_counts*100).sort_values(ascending=False)).reset_index().loc[0,groupby]
    return max_decade

In [90]:
max_decade_usa = df_category_ratio('birth_country', 'United States of America', 'decade', df_nobel)

In [121]:
df_nobel['female_winner'] = df_nobel['sex'] == 'Female'
df_female = df_nobel.groupby(['decade', 'category'], as_index=False)['female_winner'].mean()
max_female_dict = {
    df_female[df_female['female_winner'] == df_female['female_winner'].max()]['decade'].values[0]: df_female[df_female['female_winner'] == df_female['female_winner'].max()]['category'].values[0]
}
max_female_dict

{2020: 'Literature'}

In [113]:
df_female

    decade    category  female_winner
0     1900   Chemistry       0.000000
1     1900  Literature       0.100000
2     1900    Medicine       0.000000
3     1900       Peace       0.071429
4     1900     Physics       0.076923
..     ...         ...            ...
67    2020   Economics       0.111111
68    2020  Literature       0.500000
69    2020    Medicine       0.125000
70    2020       Peace       0.285714
71    2020     Physics       0.166667

[72 rows x 3 columns]